# Generated by Django 4.1.4 on 2023-01-06 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('animal_type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], max_length=3)),
                ('gender', models.CharField(choices=[('F', 'femail'), ('M', 'mail')], max_length=1)),
                ('age', models.IntegerField()),
                ('about', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.breed')),
            ],
        ),
        migrations.CreateModel(
            name='PetPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pciture', models.ImageField(upload_to='')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetPersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_warm_treated', models.BooleanField()),
                ('mood', models.CharField(choices=[('calm', 'calm'), ('energetic', 'energetic')], max_length=20)),
                ('good_treated_with_children', models.BooleanField(default=False)),
                ('trained', models.BooleanField(verbose_name='Is the animal trained?')),
                ('about', models.TextField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.color')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personality', to='pet.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('zip_code', models.CharField(max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('checked', models.BooleanField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.petlocation'),
        ),
        migrations.CreateModel(
            name='AdditionalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('pet_personality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.petpersonality')),
            ],
        ),
    ]
