# Generated by Django 4.1.4 on 2023-01-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfield',
            name='pet_personality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_field', to='pet.petpersonality'),
        ),
        migrations.AlterField(
            model_name='pethealth',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_health', to='pet.pet'),
        ),
        migrations.AlterField(
            model_name='petpicture',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_picture', to='pet.pet'),
        ),
    ]
