# Generated by Django 4.1.4 on 2023-01-28 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdopterInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('prompt_text', models.TextField(blank=True, null=True)),
                ('input_type', models.CharField(choices=[('mcss_input_options', 'Multiple Choice Single Select'), ('mcms_input_options', 'Multiple Choice Multi Select'), ('stvc_input_options', 'Simple Threshold Value Comparision'), ('na_input_options', 'Numeric Answer'), ('uf_input_options', 'Upload File')], default='mcss_input_options', max_length=50)),
                ('active_input', models.BooleanField(default=True)),
                ('adapterinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input', to='adopter.adopterinformation')),
            ],
        ),
        migrations.CreateModel(
            name='UFInputOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uf_input_options', to='adopter.input')),
            ],
        ),
        migrations.CreateModel(
            name='STVCInputOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_max', models.FloatField(blank=True, null=True)),
                ('range_min', models.FloatField(blank=True, null=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stvc_input_options', to='adopter.input')),
            ],
        ),
        migrations.CreateModel(
            name='NAInputOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(blank=True, null=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='na_input_options', to='adopter.input')),
            ],
        ),
        migrations.CreateModel(
            name='MCSSInputOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('checked', models.BooleanField(default=False)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcss_input_options', to='adopter.input')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCMSInputOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcms_input_options', to='adopter.input')),
            ],
        ),
        migrations.CreateModel(
            name='AdopterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=11)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
