# Generated by Django 4.1.4 on 2023-01-06 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdapterInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.TextField(default='', max_length=1500)),
                ('input_type', models.CharField(choices=[('MCSS', 'Multiple Choice Single Select'), ('MCMS', 'Multiple Choice Multi Select'), ('STVC', 'Simple Threshold Value Comparision'), ('NA', 'Numeric Answer'), ('UF', 'Upload File')], default='MCSS', max_length=12)),
                ('prompt_text', models.TextField(default='', max_length=800)),
                ('adapterinfo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input', to='adopter.adapterinformation')),
            ],
        ),
        migrations.CreateModel(
            name='UFInputOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uf_input_options', to='adopter.input')),
            ],
        ),
        migrations.CreateModel(
            name='STVCInputOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_max', models.FloatField()),
                ('range_min', models.FloatField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stvc_input_options', to='adopter.input')),
            ],
        ),
        migrations.CreateModel(
            name='NAInputOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='na_input_options', to='adopter.input')),
            ],
        ),
        migrations.CreateModel(
            name='MCSSInputOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('checked', models.BooleanField(default=False)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcss_input_options', to='adopter.input')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCMSInputOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcms_input_options', to='adopter.input')),
            ],
        ),
    ]
